export enum WorkflowStep {
  EXTRACTION = 'EXTRACTION',
  CLASSIFICATION = 'CLASSIFICATION',
  ACCOUNT_MAPPING = 'ACCOUNT_MAPPING',
  JOURNAL_GENERATION = 'JOURNAL_GENERATION',
  COMPLETED = 'COMPLETED',
}