/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSalesRouteImport } from './routes/dashboard.sales'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPurchasesRouteImport } from './routes/dashboard.purchases'
import { Route as DashboardOcrRouteImport } from './routes/dashboard.ocr'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardJournalRouteImport } from './routes/dashboard.journal'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardForecastingRouteImport } from './routes/dashboard.forecasting'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard.expenses'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard.assistant'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard.accounts'
import { Route as DashboardSalesReturnsRouteImport } from './routes/dashboard.sales.returns'
import { Route as DashboardSalesPaymentsRouteImport } from './routes/dashboard.sales.payments'
import { Route as DashboardSalesManageRouteImport } from './routes/dashboard.sales.manage'
import { Route as DashboardSalesCustomersRouteImport } from './routes/dashboard.sales.customers'
import { Route as DashboardSalesCreateRouteImport } from './routes/dashboard.sales.create'
import { Route as DashboardPurchasesVendorsRouteImport } from './routes/dashboard.purchases.vendors'
import { Route as DashboardPurchasesReturnsRouteImport } from './routes/dashboard.purchases.returns'
import { Route as DashboardPurchasesPaymentsRouteImport } from './routes/dashboard.purchases.payments'
import { Route as DashboardPurchasesManageRouteImport } from './routes/dashboard.purchases.manage'
import { Route as DashboardPurchasesCreateRouteImport } from './routes/dashboard.purchases.create'
import { Route as DashboardExpensesVendorsRouteImport } from './routes/dashboard.expenses.vendors'
import { Route as DashboardExpensesReturnsRouteImport } from './routes/dashboard.expenses.returns'
import { Route as DashboardExpensesPaymentsRouteImport } from './routes/dashboard.expenses.payments'
import { Route as DashboardExpensesManageRouteImport } from './routes/dashboard.expenses.manage'
import { Route as DashboardExpensesCreateRouteImport } from './routes/dashboard.expenses.create'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPurchasesRoute = DashboardPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOcrRoute = DashboardOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJournalRoute = DashboardJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastingRoute = DashboardForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesReturnsRoute = DashboardSalesReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => DashboardSalesRoute,
} as any)
const DashboardSalesPaymentsRoute = DashboardSalesPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardSalesRoute,
} as any)
const DashboardSalesManageRoute = DashboardSalesManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => DashboardSalesRoute,
} as any)
const DashboardSalesCustomersRoute = DashboardSalesCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardSalesRoute,
} as any)
const DashboardSalesCreateRoute = DashboardSalesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardSalesRoute,
} as any)
const DashboardPurchasesVendorsRoute =
  DashboardPurchasesVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => DashboardPurchasesRoute,
  } as any)
const DashboardPurchasesReturnsRoute =
  DashboardPurchasesReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => DashboardPurchasesRoute,
  } as any)
const DashboardPurchasesPaymentsRoute =
  DashboardPurchasesPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => DashboardPurchasesRoute,
  } as any)
const DashboardPurchasesManageRoute =
  DashboardPurchasesManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => DashboardPurchasesRoute,
  } as any)
const DashboardPurchasesCreateRoute =
  DashboardPurchasesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardPurchasesRoute,
  } as any)
const DashboardExpensesVendorsRoute =
  DashboardExpensesVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => DashboardExpensesRoute,
  } as any)
const DashboardExpensesReturnsRoute =
  DashboardExpensesReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => DashboardExpensesRoute,
  } as any)
const DashboardExpensesPaymentsRoute =
  DashboardExpensesPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => DashboardExpensesRoute,
  } as any)
const DashboardExpensesManageRoute = DashboardExpensesManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => DashboardExpensesRoute,
} as any)
const DashboardExpensesCreateRoute = DashboardExpensesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardExpensesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/expenses': typeof DashboardExpensesRouteWithChildren
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/ocr': typeof DashboardOcrRoute
  '/dashboard/purchases': typeof DashboardPurchasesRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sales': typeof DashboardSalesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/expenses/create': typeof DashboardExpensesCreateRoute
  '/dashboard/expenses/manage': typeof DashboardExpensesManageRoute
  '/dashboard/expenses/payments': typeof DashboardExpensesPaymentsRoute
  '/dashboard/expenses/returns': typeof DashboardExpensesReturnsRoute
  '/dashboard/expenses/vendors': typeof DashboardExpensesVendorsRoute
  '/dashboard/purchases/create': typeof DashboardPurchasesCreateRoute
  '/dashboard/purchases/manage': typeof DashboardPurchasesManageRoute
  '/dashboard/purchases/payments': typeof DashboardPurchasesPaymentsRoute
  '/dashboard/purchases/returns': typeof DashboardPurchasesReturnsRoute
  '/dashboard/purchases/vendors': typeof DashboardPurchasesVendorsRoute
  '/dashboard/sales/create': typeof DashboardSalesCreateRoute
  '/dashboard/sales/customers': typeof DashboardSalesCustomersRoute
  '/dashboard/sales/manage': typeof DashboardSalesManageRoute
  '/dashboard/sales/payments': typeof DashboardSalesPaymentsRoute
  '/dashboard/sales/returns': typeof DashboardSalesReturnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/expenses': typeof DashboardExpensesRouteWithChildren
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/ocr': typeof DashboardOcrRoute
  '/dashboard/purchases': typeof DashboardPurchasesRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sales': typeof DashboardSalesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/expenses/create': typeof DashboardExpensesCreateRoute
  '/dashboard/expenses/manage': typeof DashboardExpensesManageRoute
  '/dashboard/expenses/payments': typeof DashboardExpensesPaymentsRoute
  '/dashboard/expenses/returns': typeof DashboardExpensesReturnsRoute
  '/dashboard/expenses/vendors': typeof DashboardExpensesVendorsRoute
  '/dashboard/purchases/create': typeof DashboardPurchasesCreateRoute
  '/dashboard/purchases/manage': typeof DashboardPurchasesManageRoute
  '/dashboard/purchases/payments': typeof DashboardPurchasesPaymentsRoute
  '/dashboard/purchases/returns': typeof DashboardPurchasesReturnsRoute
  '/dashboard/purchases/vendors': typeof DashboardPurchasesVendorsRoute
  '/dashboard/sales/create': typeof DashboardSalesCreateRoute
  '/dashboard/sales/customers': typeof DashboardSalesCustomersRoute
  '/dashboard/sales/manage': typeof DashboardSalesManageRoute
  '/dashboard/sales/payments': typeof DashboardSalesPaymentsRoute
  '/dashboard/sales/returns': typeof DashboardSalesReturnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/expenses': typeof DashboardExpensesRouteWithChildren
  '/dashboard/forecasting': typeof DashboardForecastingRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/ocr': typeof DashboardOcrRoute
  '/dashboard/purchases': typeof DashboardPurchasesRouteWithChildren
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/sales': typeof DashboardSalesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/expenses/create': typeof DashboardExpensesCreateRoute
  '/dashboard/expenses/manage': typeof DashboardExpensesManageRoute
  '/dashboard/expenses/payments': typeof DashboardExpensesPaymentsRoute
  '/dashboard/expenses/returns': typeof DashboardExpensesReturnsRoute
  '/dashboard/expenses/vendors': typeof DashboardExpensesVendorsRoute
  '/dashboard/purchases/create': typeof DashboardPurchasesCreateRoute
  '/dashboard/purchases/manage': typeof DashboardPurchasesManageRoute
  '/dashboard/purchases/payments': typeof DashboardPurchasesPaymentsRoute
  '/dashboard/purchases/returns': typeof DashboardPurchasesReturnsRoute
  '/dashboard/purchases/vendors': typeof DashboardPurchasesVendorsRoute
  '/dashboard/sales/create': typeof DashboardSalesCreateRoute
  '/dashboard/sales/customers': typeof DashboardSalesCustomersRoute
  '/dashboard/sales/manage': typeof DashboardSalesManageRoute
  '/dashboard/sales/payments': typeof DashboardSalesPaymentsRoute
  '/dashboard/sales/returns': typeof DashboardSalesReturnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/select-organization'
    | '/verify-otp'
    | '/dashboard/accounts'
    | '/dashboard/assistant'
    | '/dashboard/expenses'
    | '/dashboard/forecasting'
    | '/dashboard/invoices'
    | '/dashboard/journal'
    | '/dashboard/notifications'
    | '/dashboard/ocr'
    | '/dashboard/purchases'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/expenses/create'
    | '/dashboard/expenses/manage'
    | '/dashboard/expenses/payments'
    | '/dashboard/expenses/returns'
    | '/dashboard/expenses/vendors'
    | '/dashboard/purchases/create'
    | '/dashboard/purchases/manage'
    | '/dashboard/purchases/payments'
    | '/dashboard/purchases/returns'
    | '/dashboard/purchases/vendors'
    | '/dashboard/sales/create'
    | '/dashboard/sales/customers'
    | '/dashboard/sales/manage'
    | '/dashboard/sales/payments'
    | '/dashboard/sales/returns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/select-organization'
    | '/verify-otp'
    | '/dashboard/accounts'
    | '/dashboard/assistant'
    | '/dashboard/expenses'
    | '/dashboard/forecasting'
    | '/dashboard/invoices'
    | '/dashboard/journal'
    | '/dashboard/notifications'
    | '/dashboard/ocr'
    | '/dashboard/purchases'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/admin'
    | '/dashboard'
    | '/dashboard/expenses/create'
    | '/dashboard/expenses/manage'
    | '/dashboard/expenses/payments'
    | '/dashboard/expenses/returns'
    | '/dashboard/expenses/vendors'
    | '/dashboard/purchases/create'
    | '/dashboard/purchases/manage'
    | '/dashboard/purchases/payments'
    | '/dashboard/purchases/returns'
    | '/dashboard/purchases/vendors'
    | '/dashboard/sales/create'
    | '/dashboard/sales/customers'
    | '/dashboard/sales/manage'
    | '/dashboard/sales/payments'
    | '/dashboard/sales/returns'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/select-organization'
    | '/verify-otp'
    | '/dashboard/accounts'
    | '/dashboard/assistant'
    | '/dashboard/expenses'
    | '/dashboard/forecasting'
    | '/dashboard/invoices'
    | '/dashboard/journal'
    | '/dashboard/notifications'
    | '/dashboard/ocr'
    | '/dashboard/purchases'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/transactions'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/expenses/create'
    | '/dashboard/expenses/manage'
    | '/dashboard/expenses/payments'
    | '/dashboard/expenses/returns'
    | '/dashboard/expenses/vendors'
    | '/dashboard/purchases/create'
    | '/dashboard/purchases/manage'
    | '/dashboard/purchases/payments'
    | '/dashboard/purchases/returns'
    | '/dashboard/purchases/vendors'
    | '/dashboard/sales/create'
    | '/dashboard/sales/customers'
    | '/dashboard/sales/manage'
    | '/dashboard/sales/payments'
    | '/dashboard/sales/returns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/purchases': {
      id: '/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof DashboardPurchasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ocr': {
      id: '/dashboard/ocr'
      path: '/ocr'
      fullPath: '/dashboard/ocr'
      preLoaderRoute: typeof DashboardOcrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journal': {
      id: '/dashboard/journal'
      path: '/journal'
      fullPath: '/dashboard/journal'
      preLoaderRoute: typeof DashboardJournalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecasting': {
      id: '/dashboard/forecasting'
      path: '/forecasting'
      fullPath: '/dashboard/forecasting'
      preLoaderRoute: typeof DashboardForecastingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales/returns': {
      id: '/dashboard/sales/returns'
      path: '/returns'
      fullPath: '/dashboard/sales/returns'
      preLoaderRoute: typeof DashboardSalesReturnsRouteImport
      parentRoute: typeof DashboardSalesRoute
    }
    '/dashboard/sales/payments': {
      id: '/dashboard/sales/payments'
      path: '/payments'
      fullPath: '/dashboard/sales/payments'
      preLoaderRoute: typeof DashboardSalesPaymentsRouteImport
      parentRoute: typeof DashboardSalesRoute
    }
    '/dashboard/sales/manage': {
      id: '/dashboard/sales/manage'
      path: '/manage'
      fullPath: '/dashboard/sales/manage'
      preLoaderRoute: typeof DashboardSalesManageRouteImport
      parentRoute: typeof DashboardSalesRoute
    }
    '/dashboard/sales/customers': {
      id: '/dashboard/sales/customers'
      path: '/customers'
      fullPath: '/dashboard/sales/customers'
      preLoaderRoute: typeof DashboardSalesCustomersRouteImport
      parentRoute: typeof DashboardSalesRoute
    }
    '/dashboard/sales/create': {
      id: '/dashboard/sales/create'
      path: '/create'
      fullPath: '/dashboard/sales/create'
      preLoaderRoute: typeof DashboardSalesCreateRouteImport
      parentRoute: typeof DashboardSalesRoute
    }
    '/dashboard/purchases/vendors': {
      id: '/dashboard/purchases/vendors'
      path: '/vendors'
      fullPath: '/dashboard/purchases/vendors'
      preLoaderRoute: typeof DashboardPurchasesVendorsRouteImport
      parentRoute: typeof DashboardPurchasesRoute
    }
    '/dashboard/purchases/returns': {
      id: '/dashboard/purchases/returns'
      path: '/returns'
      fullPath: '/dashboard/purchases/returns'
      preLoaderRoute: typeof DashboardPurchasesReturnsRouteImport
      parentRoute: typeof DashboardPurchasesRoute
    }
    '/dashboard/purchases/payments': {
      id: '/dashboard/purchases/payments'
      path: '/payments'
      fullPath: '/dashboard/purchases/payments'
      preLoaderRoute: typeof DashboardPurchasesPaymentsRouteImport
      parentRoute: typeof DashboardPurchasesRoute
    }
    '/dashboard/purchases/manage': {
      id: '/dashboard/purchases/manage'
      path: '/manage'
      fullPath: '/dashboard/purchases/manage'
      preLoaderRoute: typeof DashboardPurchasesManageRouteImport
      parentRoute: typeof DashboardPurchasesRoute
    }
    '/dashboard/purchases/create': {
      id: '/dashboard/purchases/create'
      path: '/create'
      fullPath: '/dashboard/purchases/create'
      preLoaderRoute: typeof DashboardPurchasesCreateRouteImport
      parentRoute: typeof DashboardPurchasesRoute
    }
    '/dashboard/expenses/vendors': {
      id: '/dashboard/expenses/vendors'
      path: '/vendors'
      fullPath: '/dashboard/expenses/vendors'
      preLoaderRoute: typeof DashboardExpensesVendorsRouteImport
      parentRoute: typeof DashboardExpensesRoute
    }
    '/dashboard/expenses/returns': {
      id: '/dashboard/expenses/returns'
      path: '/returns'
      fullPath: '/dashboard/expenses/returns'
      preLoaderRoute: typeof DashboardExpensesReturnsRouteImport
      parentRoute: typeof DashboardExpensesRoute
    }
    '/dashboard/expenses/payments': {
      id: '/dashboard/expenses/payments'
      path: '/payments'
      fullPath: '/dashboard/expenses/payments'
      preLoaderRoute: typeof DashboardExpensesPaymentsRouteImport
      parentRoute: typeof DashboardExpensesRoute
    }
    '/dashboard/expenses/manage': {
      id: '/dashboard/expenses/manage'
      path: '/manage'
      fullPath: '/dashboard/expenses/manage'
      preLoaderRoute: typeof DashboardExpensesManageRouteImport
      parentRoute: typeof DashboardExpensesRoute
    }
    '/dashboard/expenses/create': {
      id: '/dashboard/expenses/create'
      path: '/create'
      fullPath: '/dashboard/expenses/create'
      preLoaderRoute: typeof DashboardExpensesCreateRouteImport
      parentRoute: typeof DashboardExpensesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardExpensesRouteChildren {
  DashboardExpensesCreateRoute: typeof DashboardExpensesCreateRoute
  DashboardExpensesManageRoute: typeof DashboardExpensesManageRoute
  DashboardExpensesPaymentsRoute: typeof DashboardExpensesPaymentsRoute
  DashboardExpensesReturnsRoute: typeof DashboardExpensesReturnsRoute
  DashboardExpensesVendorsRoute: typeof DashboardExpensesVendorsRoute
}

const DashboardExpensesRouteChildren: DashboardExpensesRouteChildren = {
  DashboardExpensesCreateRoute: DashboardExpensesCreateRoute,
  DashboardExpensesManageRoute: DashboardExpensesManageRoute,
  DashboardExpensesPaymentsRoute: DashboardExpensesPaymentsRoute,
  DashboardExpensesReturnsRoute: DashboardExpensesReturnsRoute,
  DashboardExpensesVendorsRoute: DashboardExpensesVendorsRoute,
}

const DashboardExpensesRouteWithChildren =
  DashboardExpensesRoute._addFileChildren(DashboardExpensesRouteChildren)

interface DashboardPurchasesRouteChildren {
  DashboardPurchasesCreateRoute: typeof DashboardPurchasesCreateRoute
  DashboardPurchasesManageRoute: typeof DashboardPurchasesManageRoute
  DashboardPurchasesPaymentsRoute: typeof DashboardPurchasesPaymentsRoute
  DashboardPurchasesReturnsRoute: typeof DashboardPurchasesReturnsRoute
  DashboardPurchasesVendorsRoute: typeof DashboardPurchasesVendorsRoute
}

const DashboardPurchasesRouteChildren: DashboardPurchasesRouteChildren = {
  DashboardPurchasesCreateRoute: DashboardPurchasesCreateRoute,
  DashboardPurchasesManageRoute: DashboardPurchasesManageRoute,
  DashboardPurchasesPaymentsRoute: DashboardPurchasesPaymentsRoute,
  DashboardPurchasesReturnsRoute: DashboardPurchasesReturnsRoute,
  DashboardPurchasesVendorsRoute: DashboardPurchasesVendorsRoute,
}

const DashboardPurchasesRouteWithChildren =
  DashboardPurchasesRoute._addFileChildren(DashboardPurchasesRouteChildren)

interface DashboardSalesRouteChildren {
  DashboardSalesCreateRoute: typeof DashboardSalesCreateRoute
  DashboardSalesCustomersRoute: typeof DashboardSalesCustomersRoute
  DashboardSalesManageRoute: typeof DashboardSalesManageRoute
  DashboardSalesPaymentsRoute: typeof DashboardSalesPaymentsRoute
  DashboardSalesReturnsRoute: typeof DashboardSalesReturnsRoute
}

const DashboardSalesRouteChildren: DashboardSalesRouteChildren = {
  DashboardSalesCreateRoute: DashboardSalesCreateRoute,
  DashboardSalesCustomersRoute: DashboardSalesCustomersRoute,
  DashboardSalesManageRoute: DashboardSalesManageRoute,
  DashboardSalesPaymentsRoute: DashboardSalesPaymentsRoute,
  DashboardSalesReturnsRoute: DashboardSalesReturnsRoute,
}

const DashboardSalesRouteWithChildren = DashboardSalesRoute._addFileChildren(
  DashboardSalesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardExpensesRoute: typeof DashboardExpensesRouteWithChildren
  DashboardForecastingRoute: typeof DashboardForecastingRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardJournalRoute: typeof DashboardJournalRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOcrRoute: typeof DashboardOcrRoute
  DashboardPurchasesRoute: typeof DashboardPurchasesRouteWithChildren
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSalesRoute: typeof DashboardSalesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardExpensesRoute: DashboardExpensesRouteWithChildren,
  DashboardForecastingRoute: DashboardForecastingRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardJournalRoute: DashboardJournalRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOcrRoute: DashboardOcrRoute,
  DashboardPurchasesRoute: DashboardPurchasesRouteWithChildren,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSalesRoute: DashboardSalesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
